model:
  base_learning_rate: 4.5e-6
  target: apps.VQGAN.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: apps.VQGAN.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: apps.VQGAN.modules.dataset.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 24
    train:
      target: apps.VQGAN.data.eyepacs.ImageNetTrain
      params:
        config:
          ext: JPEG
          size: 256
          # URL: https://www.kaggle.com/competitions/diabetic-retinopathy-detection
          HOST_DIR: $KAGGLE_PATH
          NAME: eyepacs_all
          FILES:
            - eyepacs.zip
            # - train.zip.001
            # - train.zip.002
            # - train.zip.003
            # - train.zip.004
            # - train.zip.005
            # - trainLabels.csv.zip 
    validation:
      target: apps.VQGAN.data.eyepacs.ImageNetValidation
      params:
        config:
          ext: JPEG
          size: 256
