model:
  base_learning_rate: 4.5e-6
  target: apps.VQGAN.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: apps.VQGAN.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: True #False
        disc_in_channels: 6 #3
        # disc_start: 250001
        disc_start: True
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: apps.VQGAN.modules.dataset.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 2 #24
    train:
      target: apps.VQGAN.data.eyepacs.eyepacsTrain
      params:
        config:
          MODE_VAL: 200 #25 #(asli) # optianal
          EXT: jpeg
          SIZE: 256
          HOST_DIR: $KAGGLE_PATH
          NAME: eyepacs_all
          URL:
            synset: //data/config/eyepacs/synset_human.txt
            iSynset: //data/config/eyepacs/index_synset.yaml
            iSynsetTest: //data/config/eyepacs/index_synsetTest.yaml
          FILES:
            - eyepacs.zip
    validation:
      target: apps.VQGAN.data.eyepacs.eyepacsValidation
      params:
        config:
          MODE_VAL: 200 #10 #(asli) # optianal
          EXT: jpeg
          SIZE: 256
          HOST_DIR: $KAGGLE_PATH
          NAME: eyepacs_all
          URL:
            synset: //data/config/eyepacs/synset_human.txt
            iSynset: //data/config/eyepacs/index_synset.yaml
            iSynsetTest: //data/config/eyepacs/index_synsetTest.yaml
          FILES:
            - eyepacs.zip
